### PR TITLE
Add chromeless Object event management

### PR DESCRIPTION
**Pull request by paztis**
Add jsEventsMode url parameter: allow to switch between classic ExternalInterface function calls or ExternalInterface object calls

### CODE REVIEW

**Comment by mangui** [comment]
Thanks for the PR !
I think we don't need to keep legacy, supporting OOJS should be enough. And it should be straightforward to update.
Would you mind removing legacy event and updating chromeless/index.html ?
That would be really appreciated.
Merci !
Cheers, Mangui

**Comment by paztis** [comment]
Pas de problème ^^.
I do it tomorrow

2015-01-06 15:59 GMT+01:00 Guillaume du Pontavice <notifications@github.com>
:

**Comment by paztis** [comment]
Is the file examples/chromeless/example.html necessary or just
examples/chromeless/index.html ?
It's not seems to be up to date.

2015-01-06 16:50 GMT+01:00 Jérôme Hénaff <jerome.henaff@gmail.com>:

**Comment by paztis** [comment]
Ok it's done for me

**Pull request merged**
