### PR TITLE
Optionally route traffic through 3rd party proxy script.

### PR DESCRIPTION
**Pull request by redannick**
I needed this to avoid crossdomain.xml refusal. 

These changes to flashls plus https://github.com/cowboy/php-simple-proxy and a permissive crossdomain.xml on my own server allows for the playing of content otherwise not allowed by crossdomain policies.

Offered in case it's of interest.

### CODE REVIEW

**Comment by mangui** [comment]
interesting ...
@redannick 
could you fix indent and update README.md as well to describe your newly added HLSSettings ?

**Comment by redannick** [comment]
No problem. Should I add the description in README.md under ## Configuration with an 'hls_' prefix? Do these get translated to HLSSettings?

**Comment by mangui** [comment]
yes, with an 'hls_' prefix
this is translated automatically here https://github.com/mangui/flashls/blob/dev/src/org/mangui/hls/utils/Params2Settings.as#L34-L46

**Comment by redannick** [comment]
Ok I've added a description there already - how does it read to you? 

For my use case, this is working, but actually only seems to be affecting the initial m3u8 variant file... looks like all the fragments and subsequent m3u8 calls are going direct, and getting crossdomain permission from a secondary server... so I might have to patch elsewhere for the fragments etc to also go through the proxy. So as it stands in fact, the server with the proxy script is doing very little.

**Comment by mangui** [comment]
strange, fragment URL should be built here https://github.com/redannick/flashls/blob/dev/src/org/mangui/hls/playlist/Manifest.as#L272

**Comment by redannick** [comment]
Ah, yes. Ok, I'm actually removing the proxy url in `_extractURL` so that it doesn't interfere with the logic there, but wasn't replacing it before returning. If I add it back in then it does all go through the proxy. 

However it's actually quite useful for my current project to have the initial crossdomain proxied and then all the data to flow direct. The first variant playlist is on one server with no cross domain, but refers to other m3u8 files on other servers that do have permissive crossdomain files. So this way I get allowed but don't have to pay the bandwidth costs...

So would it be ok to add a settings flag to disable use of the proxy at this level? I'd guess the normal use case for this would be to have all data passing through the proxy.

**Comment by KingKebab** [comment]
Hi

Crossdomain.xml must have the same source domain name than M3U8 and TS files. This is a Flash plugin restriction.

If your domain name is forwarded by proxydomain.com because sourcedomain.com doesn't have the crossdomain.xml file, M3U8 stream must be delivered by proxydomain.com. And all video data will pass throught the proxydomain.com.

It means proxydomain.com must have a wide bandwith. To optimize your traffic you can store .TS and .M3U8 on your HTTP proxy as cache files. But, it should be easier to put a crossdomain.xml file on the sourcedomain.com.

**Comment by redannick** [comment]
Hi @KingKebab, 

By passing everything through proxydomain.com yes indeed all that data will pass through that server so you'd need plenty of bandwidth available, and yes it would be much much easier to add a permissive crossdomain.xml to sourcedomain.com. 

However if you _don't have access_ to sourcedomain.com to add or edit the crossdomain.xml there, but still need to be able to play the content hosted there, this will enable you to do it.

For example, my current project is an installation for a client who cannot give me crossdomain.xml access to their content, however it's only me who needs to access it via the proxy (It's a single installation) so the amount of bandwidth going through the proxy is minimal. In fact the server my proxy is running on is a $2 per month vps and it's doing fine. I admit it's an edge case, but it's handy to be able to work around this if you need to.

**Comment by KingKebab** [comment]
For your own use, you can install your HTTP proxy software on your own computer at home via Apache or IIS Web servers. And then, your video stream don't have to pass thought a VPS at 2$ per month ;)

**Comment by redannick** [comment]
Good idea ;)

**Comment by redannick** [comment]
I've set the proxy function to default to send all files through the proxy, but added an option to turn this off if needed (like in my case).

**Comment by ankurss** [comment]
Hate ppl stealing bandwidth, just host your own stuff or use the source player. 

this combined with gkplugins is going to ruin hundreds of sites bandwidth bill 

@mangui , would request you to remove this, as this doesn't really serves any legitimate purpose except leeching off others resources

**Comment by redannick** [comment]
I'm not stealing anyone's content - I have legitimate reasons for doing this, and the permission of the media owner to consume the content. 

In fact for my purpose I'm only avoiding the first m3u8 file as the next one in the chain is on a domain that does have a crossdomain file. The first one can't have a croddomain.xml added for various reasons.

**Comment by ankurss** [comment]
you may have the permission, "your" use maybe legitimate

but this code will allow anyone to do leech content without the protection of crossdomain.xml

**Comment by redannick** [comment]
Well, yes it could if they wanted to. However in the words of the NRA, "Code doesn't leech content, people leech content". A leecher would still have to supply their own server with the proxy code on it and pay the bandwidth costs, so it's not like the barrier to entry is a matter of switching a switch; it will cost.

There definitely are legitimate uses for this and I'd rather not have to keep my branch with it on synced manually all the time with @mangui's so accepting it would suite me. Ultimately I suppose it's up to @mangui and his conscience on the matter.

**Comment by neilrackett** [comment]
With Flash falling out of fashion, getting a `crossdomain.xml` in the right place is becoming more of an issue, particularly for short-term projects or installations, so I can definitely see legitimate use cases for a lightweight proxy.

In a perfect world, the proxy (or Flash itself) would check for CORS response headers in these scenarios, but since Flash Player doesn't support that, this appears to be a reasonable workaround for a limitation of playing HLS content in Flash.

**Pull request closed without merging**
