### PR TITLE
expose hls so we can bind to hlsevents in osmf implementation

### PR DESCRIPTION
**Pull request by swolynski**

### CODE REVIEW

**Comment by swolynski** [comment]
Hi @mangui 

This pull request is to expose the HLS object so we can bind to the level_endlist hls event that was added from @dayvson's pull request back in August...  https://github.com/mangui/flashls/pull/42  You guys ended up adding the endlist event differently (https://github.com/mangui/flashls/commit/0d652af9e7c9e0f67fe8ebd9b2e103005f7690f5) but in our osmf implementation we need an HLS reference to be able to bind the event so we can change our UI when the live stream is over.  Let us know if this works for you.

Thanks.

**Comment by mangui** [comment]
Hi @swolynski 
standard OSMF way would be to deal with stream capabilities/traits.
if there is no standard trait to notify such kind of events (switching from live to VOD) then it might be an option, even if it is hackish, to expose hls reference. just curious, why did you choose to expose hls through the Load Trait ?

**Comment by swolynski** [comment]
@mangui,  Thanks for the info.  I'll look and see if I can achieve getting the event of when the stream type switches from Live to VOD from the traits.  I was exposing the HLS object in the Load Trait since that was where I was getting the stream when the loadState was READY onLoadStateChange.  On second thought probably not the best place...  From the HLSMediaElement is probably more generic.  But I'll look to see if I can get the endlist event another way.  Thanks.

**Comment by dayvson** [comment]
Hey @mangui, 
Can you help us with that? How can we listen the endlist event using the OSMF plugin.

**Comment by mangui** [comment]
in theory when playlist is switching from live to VoD, streamingURLResource.streamType should switch to StreamType.RECORDED
refer to https://github.com/theturtle32/OSMF-AppleHLS/blob/master/OSMF/org/osmf/net/StreamType.as for stream type definition

monitoring this streamType should help detect this switch.
please note that for now this value is not modified in flashlsOSMF.
this would be a "clean" way.

**Comment by mangui** [comment]
I am merging as I didnt find any other way to notify this live => vod transition

**Comment by swolynski** [comment]
Thanks!  Yeah I was searching around and couldn't find another way either.  Thanks for the merge...  Super helpful to us....

**Comment by turbidwater** [comment]
I second that motion. This would be great to have in the main branch, as the HLS events would really help to be able to monitor. Thanks!

**Comment by turbidwater** [comment]
Whoops! I was looking at the wrong branch. Thanks for putting this into master!

**Pull request merged**
