### PR TITLE
support playback even after playbak finished

### PR DESCRIPTION
**Pull request by irazhnov**
The video finished. Try to  seek back. Playback not start after buffering finished. Hls don't  call play in this case.

### CODE REVIEW

**Comment by mangui** [comment]
@irazhnov I am not quite sure to understand the issue you are trying to fix. do you have a sample test page that exhibits the pb ?

**Comment by osmestad** [comment]
Hi, I work with Igor, the problem we are trying to solve can be replicated with these steps:
1. Open http://www.flashls.org/latest/examples/osmf/GrindPlayer.html
2. Play the video (and seek close to end if you don't like waiting :-)
3. Wait for the video to end
4. Seek somewhere in the video
5. Press play

Expected result in 5. is for video to start from seeked position, but it starts from the beginning of video.

Hope this makes it more clear what we are trying to do!

**Comment by mangui** [comment]
same scenario works fine with http://www.flashls.org/latest/examples/osmf/StrobeMediaPlayback.html
which is also OSMF based.
so at that stage, I am not sure whether there is anything broken in flashlsOSMF ?
we would need to check call sequence on OSMF trait to check whether flashlsOSMF behaves as expected by the player on top.

**Comment by irazhnov** [comment]
Hi, I think i confuse you with much details but not to point we need.
We work with OSMF based player and your hls plugin. we need next behavior. 
1.Play video to the end. (playhead stay at the end after finish).
2. seek back (video start play automatically at seek place).
Some of that behavior restricted on player side. But  i made changes which  start playback automatically after seek back. 
Current implementation in plugin don't allow me listen  HLSEvent.PLAYBACK_STATE, it available in flow player only. That means buffering finished after seek but, playback not start.
My changes don't break common logic.  playback behavior play/pause not change after seek during common playback.
Hope i explain more clear.

**Comment by osmestad** [comment]
Thank you!

**Pull request merged**
