### PR TITLE
retry primary stream after failing with all redundant streams

### PR DESCRIPTION
**Pull request by ivantenger**
With this change LevelLoader._errorHandler will retry the primary stream url after failing with all redundant stream urls. This behaviour is useful when primary stream is only temporarily down.

### CODE REVIEW

**Comment by ysle** [comment]
:+1:  thanks!

**Comment by mangui** [comment]
thanks @ivantenger this can indeed help in case you got I/O error on your live playlist.... in that case i can understand that rotating through redundant stream can be an option.
the issue is that it will keep rotating forever if all streams are down, without reporting any error ...

IMHO the nb of redundant stream switch should be capped with an HLSSettings.
you can eventually set the capping value to -1 to tell him to keep retrying forever if you need such behaviour.

I think that it would also make sense to follow a similar approach for fragment loading : 
https://github.com/mangui/flashls/blob/dev/src/org/mangui/hls/loader/FragmentLoader.as#L436-L445

as you can see, in case of frag I/O error, frag loader will switch to next redundant stream if any, until we reach the last redundant one...

**Comment by mangui** [comment]
@ivantenger 
I would consider merging your PR if you add an HLSSettings to cap the nb of rotation on the redundant streams. let me know your though
Mangui

**Comment by ivantenger** [comment]
Yes, this solution is suitable for us. 

To sum there will be a new HLSSettings.maxRotateStreams wich caps the number of rotations, -1 means "rotate for ever".

Shout if you prefer another name for it. Otherwise I'll modify the pull request soon.

**Comment by mangui** [comment]
to keep it consistent with already existing keys, I would suggest

```
HLSSettings.manifestRedundantLoadmaxRetry
```

**Comment by ivantenger** [comment]
Sure, no problem.

**Comment by ivantenger** [comment]
Please check if this implementation is OK for you. Thanks, Ivan.

**Comment by mangui** [comment]
bin/flashhls_backupstream.swc has been commited by mistake, could you remove it ?

**Comment by mangui** [comment]
while looking at https://patch-diff.githubusercontent.com/raw/mangui/flashls/pull/430.diff,
we can see unaligned indents. I suspect that you are using tabs instead of space ?

**Comment by ivantenger** [comment]
Done.

**Pull request merged**
