### PR TITLE
Remove hardcoded callback function names from Chromeless player

### PR DESCRIPTION
**Pull request by karl**
This is the same changes as in https://github.com/mangui/flashls/pull/244 but for the `master` branch.

We are using this change in production, so it makes sense for us to have it in the release branch.

You may want to merge it in if you feel it doesn't require waiting for the `dev` branch to become stable enough to release.

### CODE REVIEW

**Comment by mangui** [comment]
i cannot merge this one because of swf/swc file, could you remove them from the PR ? thanks

**Comment by karl** [comment]
Sure I'll do that once I'm back in work tomorrow!

**Comment by karl** [comment]
The merge was failing due to my previous pull request having been merged :) I've fixed this up now, and the pull request can now be merged automatically.

It still contains the compiled `.swf` and `.swc` files, but I can remove them if you'd like!

**Comment by karl** [comment]
Thanks!

**Pull request merged**
